<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Store\Grpc\ResourceVideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.ResourceVideo.Cover</code>
 */
class Cover extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 w = 1;</code>
     */
    protected $w = 0;
    /**
     * Generated from protobuf field <code>int32 h = 2;</code>
     */
    protected $h = 0;
    /**
     * Generated from protobuf field <code>string url = 3;</code>
     */
    protected $url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $w
     *     @type int $h
     *     @type string $url
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 w = 1;</code>
     * @return int
     */
    public function getW()
    {
        return $this->w;
    }

    /**
     * Generated from protobuf field <code>int32 w = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setW($var)
    {
        GPBUtil::checkInt32($var);
        $this->w = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 h = 2;</code>
     * @return int
     */
    public function getH()
    {
        return $this->h;
    }

    /**
     * Generated from protobuf field <code>int32 h = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setH($var)
    {
        GPBUtil::checkInt32($var);
        $this->h = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 3;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Cover::class, \Store\Grpc\ResourceVideo_Cover::class);

