<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Store\Grpc\ResourceVideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.ResourceVideo.Ext</code>
 */
class Ext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 w = 1;</code>
     */
    protected $w = 0;
    /**
     * Generated from protobuf field <code>int32 h = 2;</code>
     */
    protected $h = 0;
    /**
     * Generated from protobuf field <code>string mime = 3;</code>
     */
    protected $mime = '';
    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.ResourceVideo.Cover cover = 4;</code>
     */
    protected $cover = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $w
     *     @type int $h
     *     @type string $mime
     *     @type \Store\Grpc\ResourceVideo\Cover $cover
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 w = 1;</code>
     * @return int
     */
    public function getW()
    {
        return $this->w;
    }

    /**
     * Generated from protobuf field <code>int32 w = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setW($var)
    {
        GPBUtil::checkInt32($var);
        $this->w = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 h = 2;</code>
     * @return int
     */
    public function getH()
    {
        return $this->h;
    }

    /**
     * Generated from protobuf field <code>int32 h = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setH($var)
    {
        GPBUtil::checkInt32($var);
        $this->h = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mime = 3;</code>
     * @return string
     */
    public function getMime()
    {
        return $this->mime;
    }

    /**
     * Generated from protobuf field <code>string mime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMime($var)
    {
        GPBUtil::checkString($var, True);
        $this->mime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.ResourceVideo.Cover cover = 4;</code>
     * @return \Store\Grpc\ResourceVideo\Cover
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.ResourceVideo.Cover cover = 4;</code>
     * @param \Store\Grpc\ResourceVideo\Cover $var
     * @return $this
     */
    public function setCover($var)
    {
        GPBUtil::checkMessage($var, \Store\Grpc\ResourceVideo_Cover::class);
        $this->cover = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Ext::class, \Store\Grpc\ResourceVideo_Ext::class);

