<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.DeleteStoreRep</code>
 */
class DeleteStoreRep extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

}

