<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.EditStoreReq</code>
 */
class EditStoreReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     */
    protected $Id = 0;
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>int32 type = 3;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>string cover = 5;</code>
     */
    protected $cover = '';
    /**
     * Generated from protobuf field <code>string images = 6;</code>
     */
    protected $images = '';
    /**
     * Generated from protobuf field <code>string videos = 7;</code>
     */
    protected $videos = '';
    /**
     * Generated from protobuf field <code>string brand_ids = 8;</code>
     */
    protected $brand_ids = '';
    /**
     * Generated from protobuf field <code>string dealer_ids = 9;</code>
     */
    protected $dealer_ids = '';
    /**
     * Generated from protobuf field <code>string gaode_id = 10;</code>
     */
    protected $gaode_id = '';
    /**
     * Generated from protobuf field <code>int32 province_code = 11;</code>
     */
    protected $province_code = 0;
    /**
     * Generated from protobuf field <code>int32 city_code = 12;</code>
     */
    protected $city_code = 0;
    /**
     * Generated from protobuf field <code>int32 area_code = 13;</code>
     */
    protected $area_code = 0;
    /**
     * Generated from protobuf field <code>int32 source = 14;</code>
     */
    protected $source = 0;
    /**
     * Generated from protobuf field <code>string tag_ids = 15;</code>
     */
    protected $tag_ids = '';
    /**
     * Generated from protobuf field <code>string address = 16;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string tel = 17;</code>
     */
    protected $tel = '';
    /**
     * Generated from protobuf field <code>string gcj_02 = 18;</code>
     */
    protected $gcj_02 = '';
    /**
     * Generated from protobuf field <code>string location = 19;</code>
     */
    protected $location = '';
    /**
     * Generated from protobuf field <code>int32 district_id = 20;</code>
     */
    protected $district_id = 0;
    /**
     * Generated from protobuf field <code>string wechat = 21;</code>
     */
    protected $wechat = '';
    /**
     * Generated from protobuf field <code>string introduction = 23;</code>
     */
    protected $introduction = '';
    /**
     * Generated from protobuf field <code>string brand_names = 24;</code>
     */
    protected $brand_names = '';
    /**
     * Generated from protobuf field <code>string styles = 25;</code>
     */
    protected $styles = '';
    /**
     * Generated from protobuf field <code>string products = 26;</code>
     */
    protected $products = '';
    /**
     * Generated from protobuf field <code>string price_descs = 27;</code>
     */
    protected $price_descs = '';
    /**
     * Generated from protobuf field <code>string business_time = 28;</code>
     */
    protected $business_time = '';
    /**
     * Generated from protobuf field <code>string province_name = 29;</code>
     */
    protected $province_name = '';
    /**
     * Generated from protobuf field <code>string city_name = 30;</code>
     */
    protected $city_name = '';
    /**
     * Generated from protobuf field <code>string area_name = 31;</code>
     */
    protected $area_name = '';
    /**
     * Generated from protobuf field <code>int32 status = 32;</code>
     */
    protected $status = 0;
    /**
     * 可以为空,迁移数据用
     *
     * Generated from protobuf field <code>int32 articles = 33;</code>
     */
    protected $articles = 0;
    /**
     * 评价数
     *
     * Generated from protobuf field <code>int32 evaluations = 34;</code>
     */
    protected $evaluations = 0;
    /**
     * 商品数
     *
     * Generated from protobuf field <code>int32 items = 35;</code>
     */
    protected $items = 0;
    /**
     * 真实点击数
     *
     * Generated from protobuf field <code>int32 realClicks = 36;</code>
     */
    protected $realClicks = 0;
    /**
     * 点击数
     *
     * Generated from protobuf field <code>int32 clicks = 37;</code>
     */
    protected $clicks = 0;
    /**
     * 旧表的门店id
     *
     * Generated from protobuf field <code>int32 original_id = 38;</code>
     */
    protected $original_id = 0;
    /**
     * 认证时间
     *
     * Generated from protobuf field <code>int32 status_time = 39;</code>
     */
    protected $status_time = 0;
    /**
     * 上下架
     *
     * Generated from protobuf field <code>int32 displayorder = 40;</code>
     */
    protected $displayorder = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Id
     *     @type string $title
     *     @type int $type
     *     @type int $level
     *     @type string $cover
     *     @type string $images
     *     @type string $videos
     *     @type string $brand_ids
     *     @type string $dealer_ids
     *     @type string $gaode_id
     *     @type int $province_code
     *     @type int $city_code
     *     @type int $area_code
     *     @type int $source
     *     @type string $tag_ids
     *     @type string $address
     *     @type string $tel
     *     @type string $gcj_02
     *     @type string $location
     *     @type int $district_id
     *     @type string $wechat
     *     @type string $introduction
     *     @type string $brand_names
     *     @type string $styles
     *     @type string $products
     *     @type string $price_descs
     *     @type string $business_time
     *     @type string $province_name
     *     @type string $city_name
     *     @type string $area_name
     *     @type int $status
     *     @type int $articles
     *           可以为空,迁移数据用
     *     @type int $evaluations
     *           评价数
     *     @type int $items
     *           商品数
     *     @type int $realClicks
     *           真实点击数
     *     @type int $clicks
     *           点击数
     *     @type int $original_id
     *           旧表的门店id
     *     @type int $status_time
     *           认证时间
     *     @type int $displayorder
     *           上下架
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cover = 5;</code>
     * @return string
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     * Generated from protobuf field <code>string cover = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCover($var)
    {
        GPBUtil::checkString($var, True);
        $this->cover = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string images = 6;</code>
     * @return string
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Generated from protobuf field <code>string images = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setImages($var)
    {
        GPBUtil::checkString($var, True);
        $this->images = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videos = 7;</code>
     * @return string
     */
    public function getVideos()
    {
        return $this->videos;
    }

    /**
     * Generated from protobuf field <code>string videos = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVideos($var)
    {
        GPBUtil::checkString($var, True);
        $this->videos = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string brand_ids = 8;</code>
     * @return string
     */
    public function getBrandIds()
    {
        return $this->brand_ids;
    }

    /**
     * Generated from protobuf field <code>string brand_ids = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBrandIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dealer_ids = 9;</code>
     * @return string
     */
    public function getDealerIds()
    {
        return $this->dealer_ids;
    }

    /**
     * Generated from protobuf field <code>string dealer_ids = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDealerIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->dealer_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gaode_id = 10;</code>
     * @return string
     */
    public function getGaodeId()
    {
        return $this->gaode_id;
    }

    /**
     * Generated from protobuf field <code>string gaode_id = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setGaodeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->gaode_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 province_code = 11;</code>
     * @return int
     */
    public function getProvinceCode()
    {
        return $this->province_code;
    }

    /**
     * Generated from protobuf field <code>int32 province_code = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setProvinceCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->province_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 city_code = 12;</code>
     * @return int
     */
    public function getCityCode()
    {
        return $this->city_code;
    }

    /**
     * Generated from protobuf field <code>int32 city_code = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setCityCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->city_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 area_code = 13;</code>
     * @return int
     */
    public function getAreaCode()
    {
        return $this->area_code;
    }

    /**
     * Generated from protobuf field <code>int32 area_code = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setAreaCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->area_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 source = 14;</code>
     * @return int
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>int32 source = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkInt32($var);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag_ids = 15;</code>
     * @return string
     */
    public function getTagIds()
    {
        return $this->tag_ids;
    }

    /**
     * Generated from protobuf field <code>string tag_ids = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setTagIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 16;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tel = 17;</code>
     * @return string
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     * Generated from protobuf field <code>string tel = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setTel($var)
    {
        GPBUtil::checkString($var, True);
        $this->tel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gcj_02 = 18;</code>
     * @return string
     */
    public function getGcj02()
    {
        return $this->gcj_02;
    }

    /**
     * Generated from protobuf field <code>string gcj_02 = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setGcj02($var)
    {
        GPBUtil::checkString($var, True);
        $this->gcj_02 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string location = 19;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>string location = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 district_id = 20;</code>
     * @return int
     */
    public function getDistrictId()
    {
        return $this->district_id;
    }

    /**
     * Generated from protobuf field <code>int32 district_id = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setDistrictId($var)
    {
        GPBUtil::checkInt32($var);
        $this->district_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wechat = 21;</code>
     * @return string
     */
    public function getWechat()
    {
        return $this->wechat;
    }

    /**
     * Generated from protobuf field <code>string wechat = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setWechat($var)
    {
        GPBUtil::checkString($var, True);
        $this->wechat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string introduction = 23;</code>
     * @return string
     */
    public function getIntroduction()
    {
        return $this->introduction;
    }

    /**
     * Generated from protobuf field <code>string introduction = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setIntroduction($var)
    {
        GPBUtil::checkString($var, True);
        $this->introduction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string brand_names = 24;</code>
     * @return string
     */
    public function getBrandNames()
    {
        return $this->brand_names;
    }

    /**
     * Generated from protobuf field <code>string brand_names = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setBrandNames($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand_names = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string styles = 25;</code>
     * @return string
     */
    public function getStyles()
    {
        return $this->styles;
    }

    /**
     * Generated from protobuf field <code>string styles = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setStyles($var)
    {
        GPBUtil::checkString($var, True);
        $this->styles = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string products = 26;</code>
     * @return string
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * Generated from protobuf field <code>string products = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setProducts($var)
    {
        GPBUtil::checkString($var, True);
        $this->products = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string price_descs = 27;</code>
     * @return string
     */
    public function getPriceDescs()
    {
        return $this->price_descs;
    }

    /**
     * Generated from protobuf field <code>string price_descs = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setPriceDescs($var)
    {
        GPBUtil::checkString($var, True);
        $this->price_descs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string business_time = 28;</code>
     * @return string
     */
    public function getBusinessTime()
    {
        return $this->business_time;
    }

    /**
     * Generated from protobuf field <code>string business_time = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setBusinessTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->business_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string province_name = 29;</code>
     * @return string
     */
    public function getProvinceName()
    {
        return $this->province_name;
    }

    /**
     * Generated from protobuf field <code>string province_name = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setProvinceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->province_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city_name = 30;</code>
     * @return string
     */
    public function getCityName()
    {
        return $this->city_name;
    }

    /**
     * Generated from protobuf field <code>string city_name = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setCityName($var)
    {
        GPBUtil::checkString($var, True);
        $this->city_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string area_name = 31;</code>
     * @return string
     */
    public function getAreaName()
    {
        return $this->area_name;
    }

    /**
     * Generated from protobuf field <code>string area_name = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setAreaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->area_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 32;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 32;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * 可以为空,迁移数据用
     *
     * Generated from protobuf field <code>int32 articles = 33;</code>
     * @return int
     */
    public function getArticles()
    {
        return $this->articles;
    }

    /**
     * 可以为空,迁移数据用
     *
     * Generated from protobuf field <code>int32 articles = 33;</code>
     * @param int $var
     * @return $this
     */
    public function setArticles($var)
    {
        GPBUtil::checkInt32($var);
        $this->articles = $var;

        return $this;
    }

    /**
     * 评价数
     *
     * Generated from protobuf field <code>int32 evaluations = 34;</code>
     * @return int
     */
    public function getEvaluations()
    {
        return $this->evaluations;
    }

    /**
     * 评价数
     *
     * Generated from protobuf field <code>int32 evaluations = 34;</code>
     * @param int $var
     * @return $this
     */
    public function setEvaluations($var)
    {
        GPBUtil::checkInt32($var);
        $this->evaluations = $var;

        return $this;
    }

    /**
     * 商品数
     *
     * Generated from protobuf field <code>int32 items = 35;</code>
     * @return int
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * 商品数
     *
     * Generated from protobuf field <code>int32 items = 35;</code>
     * @param int $var
     * @return $this
     */
    public function setItems($var)
    {
        GPBUtil::checkInt32($var);
        $this->items = $var;

        return $this;
    }

    /**
     * 真实点击数
     *
     * Generated from protobuf field <code>int32 realClicks = 36;</code>
     * @return int
     */
    public function getRealClicks()
    {
        return $this->realClicks;
    }

    /**
     * 真实点击数
     *
     * Generated from protobuf field <code>int32 realClicks = 36;</code>
     * @param int $var
     * @return $this
     */
    public function setRealClicks($var)
    {
        GPBUtil::checkInt32($var);
        $this->realClicks = $var;

        return $this;
    }

    /**
     * 点击数
     *
     * Generated from protobuf field <code>int32 clicks = 37;</code>
     * @return int
     */
    public function getClicks()
    {
        return $this->clicks;
    }

    /**
     * 点击数
     *
     * Generated from protobuf field <code>int32 clicks = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setClicks($var)
    {
        GPBUtil::checkInt32($var);
        $this->clicks = $var;

        return $this;
    }

    /**
     * 旧表的门店id
     *
     * Generated from protobuf field <code>int32 original_id = 38;</code>
     * @return int
     */
    public function getOriginalId()
    {
        return $this->original_id;
    }

    /**
     * 旧表的门店id
     *
     * Generated from protobuf field <code>int32 original_id = 38;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginalId($var)
    {
        GPBUtil::checkInt32($var);
        $this->original_id = $var;

        return $this;
    }

    /**
     * 认证时间
     *
     * Generated from protobuf field <code>int32 status_time = 39;</code>
     * @return int
     */
    public function getStatusTime()
    {
        return $this->status_time;
    }

    /**
     * 认证时间
     *
     * Generated from protobuf field <code>int32 status_time = 39;</code>
     * @param int $var
     * @return $this
     */
    public function setStatusTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->status_time = $var;

        return $this;
    }

    /**
     * 上下架
     *
     * Generated from protobuf field <code>int32 displayorder = 40;</code>
     * @return int
     */
    public function getDisplayorder()
    {
        return $this->displayorder;
    }

    /**
     * 上下架
     *
     * Generated from protobuf field <code>int32 displayorder = 40;</code>
     * @param int $var
     * @return $this
     */
    public function setDisplayorder($var)
    {
        GPBUtil::checkInt32($var);
        $this->displayorder = $var;

        return $this;
    }

}

