<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.OfflineStoreDetailRep</code>
 */
class OfflineStoreDetailRep extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.OfflineStore offline_store = 1;</code>
     */
    protected $offline_store = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Store\Grpc\OfflineStore $offline_store
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.OfflineStore offline_store = 1;</code>
     * @return \Store\Grpc\OfflineStore
     */
    public function getOfflineStore()
    {
        return $this->offline_store;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.OfflineStore offline_store = 1;</code>
     * @param \Store\Grpc\OfflineStore $var
     * @return $this
     */
    public function setOfflineStore($var)
    {
        GPBUtil::checkMessage($var, \Store\Grpc\OfflineStore::class);
        $this->offline_store = $var;

        return $this;
    }

}

