<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.OnlineStoreDetailRep</code>
 */
class OnlineStoreDetailRep extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.OnlineStore online_store = 1;</code>
     */
    protected $online_store = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Store\Grpc\OnlineStore $online_store
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.OnlineStore online_store = 1;</code>
     * @return \Store\Grpc\OnlineStore
     */
    public function getOnlineStore()
    {
        return $this->online_store;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.OnlineStore online_store = 1;</code>
     * @param \Store\Grpc\OnlineStore $var
     * @return $this
     */
    public function setOnlineStore($var)
    {
        GPBUtil::checkMessage($var, \Store\Grpc\OnlineStore::class);
        $this->online_store = $var;

        return $this;
    }

}

