<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Store\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Store\Grpc\ResourceVideo\Cover instead.
     * @deprecated
     */
    class ResourceVideo_Cover {}
}
class_exists(ResourceVideo\Cover::class);
@trigger_error('Store\Grpc\ResourceVideo_Cover is deprecated and will be removed in the next major release. Use Store\Grpc\ResourceVideo\Cover instead', E_USER_DEPRECATED);

