<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.ResourceImage</code>
 */
class ResourceImage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string data = 2;</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.ResourceImage.Ext ext = 3;</code>
     */
    protected $ext = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $data
     *     @type \Store\Grpc\ResourceImage\Ext $ext
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.ResourceImage.Ext ext = 3;</code>
     * @return \Store\Grpc\ResourceImage\Ext
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.ResourceImage.Ext ext = 3;</code>
     * @param \Store\Grpc\ResourceImage\Ext $var
     * @return $this
     */
    public function setExt($var)
    {
        GPBUtil::checkMessage($var, \Store\Grpc\ResourceImage_Ext::class);
        $this->ext = $var;

        return $this;
    }

}

