<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Store\Grpc;

if (false) {
    /**
     * This class is deprecated. Use Store\Grpc\ResourceImage\Ext instead.
     * @deprecated
     */
    class ResourceImage_Ext {}
}
class_exists(ResourceImage\Ext::class);
@trigger_error('Store\Grpc\ResourceImage_Ext is deprecated and will be removed in the next major release. Use Store\Grpc\ResourceImage\Ext instead', E_USER_DEPRECATED);

