<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.StoreListRep</code>
 */
class StoreListRep extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .go.micro.srv.store.v1.Store store = 1;</code>
     */
    private $store;
    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.Page page = 2;</code>
     */
    protected $page = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Store\Grpc\Store[]|\Google\Protobuf\Internal\RepeatedField $store
     *     @type \Store\Grpc\Page $page
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .go.micro.srv.store.v1.Store store = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStore()
    {
        return $this->store;
    }

    /**
     * Generated from protobuf field <code>repeated .go.micro.srv.store.v1.Store store = 1;</code>
     * @param \Store\Grpc\Store[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStore($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Store\Grpc\Store::class);
        $this->store = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.Page page = 2;</code>
     * @return \Store\Grpc\Page
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>.go.micro.srv.store.v1.Page page = 2;</code>
     * @param \Store\Grpc\Page $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Store\Grpc\Page::class);
        $this->page = $var;

        return $this;
    }

}

