<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.StoreVideoListRep</code>
 */
class StoreVideoListRep extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .go.micro.srv.store.v1.ResourceVideo video = 1;</code>
     */
    private $video;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Store\Grpc\ResourceVideo[]|\Google\Protobuf\Internal\RepeatedField $video
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .go.micro.srv.store.v1.ResourceVideo video = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVideo()
    {
        return $this->video;
    }

    /**
     * Generated from protobuf field <code>repeated .go.micro.srv.store.v1.ResourceVideo video = 1;</code>
     * @param \Store\Grpc\ResourceVideo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVideo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Store\Grpc\ResourceVideo::class);
        $this->video = $arr;

        return $this;
    }

}

