<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace Store\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>go.micro.srv.store.v1.StoreListReq</code>
 */
class StoreListReq extends \Google\Protobuf\Internal\Message
{
    /**
     * 类型
     *
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    /**
     * 经销商id
     *
     * Generated from protobuf field <code>int32 dealer_id = 2;</code>
     */
    protected $dealer_id = 0;
    /**
     * 品牌id
     *
     * Generated from protobuf field <code>int32 brand_id = 3;</code>
     */
    protected $brand_id = 0;
    /**
     * 城市
     *
     * Generated from protobuf field <code>string city = 4;</code>
     */
    protected $city = '';
    /**
     * 街区id
     *
     * Generated from protobuf field <code>int32 district_id = 5;</code>
     */
    protected $district_id = 0;
    /**
     * 定位
     *
     * Generated from protobuf field <code>string location = 6;</code>
     */
    protected $location = '';
    /**
     * 分类
     *
     * Generated from protobuf field <code>string tag = 7;</code>
     */
    protected $tag = '';
    /**
     * 排序
     *
     * Generated from protobuf field <code>string order = 8;</code>
     */
    protected $order = '';
    /**
     * 距离
     *
     * Generated from protobuf field <code>string distance = 9;</code>
     */
    protected $distance = '';
    /**
     * Generated from protobuf field <code>int32 page = 10;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int32 page_size = 11;</code>
     */
    protected $page_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           类型
     *     @type int $dealer_id
     *           经销商id
     *     @type int $brand_id
     *           品牌id
     *     @type string $city
     *           城市
     *     @type int $district_id
     *           街区id
     *     @type string $location
     *           定位
     *     @type string $tag
     *           分类
     *     @type string $order
     *           排序
     *     @type string $distance
     *           距离
     *     @type int $page
     *     @type int $page_size
     * }
     */
    public function __construct($data = NULL) {
        \Store\Grpc\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * 类型
     *
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * 类型
     *
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * 经销商id
     *
     * Generated from protobuf field <code>int32 dealer_id = 2;</code>
     * @return int
     */
    public function getDealerId()
    {
        return $this->dealer_id;
    }

    /**
     * 经销商id
     *
     * Generated from protobuf field <code>int32 dealer_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDealerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->dealer_id = $var;

        return $this;
    }

    /**
     * 品牌id
     *
     * Generated from protobuf field <code>int32 brand_id = 3;</code>
     * @return int
     */
    public function getBrandId()
    {
        return $this->brand_id;
    }

    /**
     * 品牌id
     *
     * Generated from protobuf field <code>int32 brand_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBrandId($var)
    {
        GPBUtil::checkInt32($var);
        $this->brand_id = $var;

        return $this;
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string city = 4;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string city = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * 街区id
     *
     * Generated from protobuf field <code>int32 district_id = 5;</code>
     * @return int
     */
    public function getDistrictId()
    {
        return $this->district_id;
    }

    /**
     * 街区id
     *
     * Generated from protobuf field <code>int32 district_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDistrictId($var)
    {
        GPBUtil::checkInt32($var);
        $this->district_id = $var;

        return $this;
    }

    /**
     * 定位
     *
     * Generated from protobuf field <code>string location = 6;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * 定位
     *
     * Generated from protobuf field <code>string location = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;

        return $this;
    }

    /**
     * 分类
     *
     * Generated from protobuf field <code>string tag = 7;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * 分类
     *
     * Generated from protobuf field <code>string tag = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>string order = 8;</code>
     * @return string
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>string order = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkString($var, True);
        $this->order = $var;

        return $this;
    }

    /**
     * 距离
     *
     * Generated from protobuf field <code>string distance = 9;</code>
     * @return string
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * 距离
     *
     * Generated from protobuf field <code>string distance = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDistance($var)
    {
        GPBUtil::checkString($var, True);
        $this->distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 10;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 11;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

}

