<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter_test.proto

namespace Service\Testbo\GPBMetadata\V1;

class GreeterTest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab8010a12677265657465725f746573742e70726f746f22170a0752657175657374120c0a046e616d65180120012809221c0a08526573706f6e736512100a086772656574696e67180120012809322d0a0b4772656574657254657374121e0a0548656c6c6f12082e526571756573741a092e526573706f6e736522004234ca0211536572766963655c54657374626f5c5631e2021d536572766963655c54657374626f5c4750424d657461646174615c5631620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

